### ISSUE TITLE
Local paths

### ISSUE THREAD

**Issue by sielay** [pboysen/prosemirror-widgets#1]
Hi, nice examples, but if you want to use local checkout of prose mirror you can use https://docs.npmjs.com/cli/link

Something like https://github.com/pboysen/prosemirror-widgets/blob/master/src/utils/params.js#L1 hurst eyes a bit.

Except this, nice work

**Comment by pboysen** [comment]
Thanks.  I am fairly new to npm so can use all the help I can get.

**Comment by pboysen** [comment]
Linked my project to the prosemirror distribution

**Comment by sielay** [comment]
Happy I could help. Hope you don't mind comments. Best way to get better. Feel free to review any of my code. Cheers.

**Comment by pboysen** [comment]
No problem.  I put it out there to get the community excited about possibilities.  It is far from perfect.
